config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root   'questions#index'
  resources :questions do
  	resources :comments, module: :questions
  	resources :votes, module: :questions
  	resources :answers do
  	  resources :comments, module: :answers
  	  resources :votes, module: :answers
  	end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
	
	belongs_to :question
	belongs_to :user
	has_many :comments, as: :commentable, dependent: :destroy
	has_many :votes, as: :votable


	def voted?(current_user)
		votes.exists?(user: current_user)
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
end

app/models/question.rb
class Question < ApplicationRecord
	belongs_to :user
	has_many :answers
	has_many :comments, as: :commentable, dependent: :destroy
	has_many :votes, as: :votable

	def score
		votes.count
	end

	def voted?(current_user)
		votes.exists?(user: current_user)
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :questions
  has_many :answers
  has_many :votes
 
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :votable, polymorphic: true
  belongs_to :user

 
end

app/controllers/answers/comments_controller.rb
class Answers::CommentsController < CommentsController
	before_action :set_commentable




	private

	def set_commentable
		@commentable = Answer.find(params[:answer_id])
	end
end

app/controllers/answers/votes_controller.rb
class Answers::VotesController < VotesController
	before_action :set_votable


	private
    def set_votable
      @votable = Answer.find(params[:answer_id])
    end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
	before_action :authenticate_user!, only: [:create, :edit, :update, :destroy]

	def index
		@answers = Answers.all
	end

	def create
		@answer = Answer.new(answer_params)
		@answer.user_id == current_user.id
		if @answer.save
			flash[:success] = 'La respuesta ha sido registrada con éxito.'
	  end
	    redirect_to question_path(params[:question_id])
	end

	def edit
  end

  def update
    if @answer.update(answer_params)
      flash[:success] = 'La respuesta ha sido actualizada con éxito.'
    end
      redirect_to question_path(params[:question_id])
  end

  def destroy
    @answer = Answer.find_by(question_id: params[:question_id], id: params[:id])
    if @answer.destroy
      flash[:success] = 'La respuesta ha sido eliminada con éxito.'
    end
      redirect_to question_path(params[:question_id])
  end

  private
    def answer_params
      params.require(:answer)
        .permit(:answer_body)
        .merge(user_id: current_user.id, question_id: params[:question_id])
    end




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	

	def index
		@comments = Comment.all
	end

	def new
		@comment = @commentable.comments.new
	end

	def create
		@comment = @commentable.comments.new(comment_params)
		if @comment.save
		  flash[:success] = 'El comentario ha sido registrado con éxito.'
		end
	end

	private
		def comment_params
			params.require(:comment).permit(:body)
		end

		
end

app/controllers/questions/comments_controller.rb
class Questions::CommentsController < CommentsController
	before_action :set_commentable




	private

	def set_commentable
		@commentable = Question.find(params[:question_id])
	end
end

app/controllers/questions/votes_controller.rb
class Questions::VotesController < VotesController
	before_action :set_votable


	private
     def set_votable
      @votable = Question.find(params[:question_id])
    end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update]

	def index
		@questions = Question.all.order(created_at: :desc).limit(10)
	end

	def show
		@question = Question.find(params[:id])
		@answer  = Answer.new
		@answers = @question.answers.all.order(created_at: :asc).limit(10)
	end

	def new
		@question = Question.new
	end

	def edit
		@question = Question.find(params[:id])
	end

	def update
		if @question.update(question_params)
      flash[:success] = 'La pregunta ha sido actualizada con éxito.'
      redirect_to questions_path
    else
      render :edit
    end
	end

	def create
		@question = current_user.questions.new(question_params)
    if @question.save
      flash[:success] = 'La pregunta ha sido creada con éxito.'
      redirect_to questions_path
    else
      render :new
    end
	end

	def destroy
    @question.destroy
    flash[:success] = 'La pregunta ha sido eliminada con éxito.'
    redirect_to questions_path
  end

  private
    def set_question
      @question = Question.find(params[:id])
    end
     def question_params
      params.require(:question).permit(:title, :body)
    end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
	before_action :authenticate_user!
	

	def index
		@votes = Vote.all
	end


	def create
		@vote = @votable.votes.create(user_id: current_user.id)
		if @vote.save
		  flash[:success] = 'Tu voto ha sido guardado'
		end
	end

	def destroy
    @vote = @votable.votes.take.try(:destroy)
  end

		

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/_answer.html.erb
<div class="answer" data-id="<%= answer.id %>">
  <table>
    <tbody>
      <tr>
        <td class="votecell">
          <div class="votes">
            <%= render 'votes/votes', votable: answer,
                                      create_url_path: question_answer_votes_path(answer.question, answer),
                                      destroy_url_path: question_answer_vote_path(answer.question, answer) %>
          </div>
        </td>
        <td class="answer__cell">
          <div class="answer__body">
            <p>
              <%=  answer.answer_body %>
            </p>
            <table class="answer__footer">
              <tbody>
                <tr>
                  <td class="vt">
                    <% if user_signed_in? && answer.user == current_user %>
                      <div class="answer__actions">
                        <ul>
                          <li>
                            <%= link_to " <span class='glyphicon glyphicon-pencil'></span> Editar"
                                  .html_safe,
                                  edit_question_answer_path(answer.question, answer) %>
                          </li>
                          <li>
                            <%= link_to " <span class='glyphicon glyphicon-trash'></span> Eliminar"
                                  .html_safe,
                                  question_answer_path(answer.question, answer),
                                  method: :delete,
                                  data: { confirm: "¿Estás seguro de eliminar esta respuesta?" } %>
                          </li>
                        </ul>
                      </div>
                    <% end %>
                  </td>
                  <td class="user-signature">
                    <div class="user-action-time">
                      contestada hace <%= time_ago_in_words answer.created_at %>
                    </div>
                    <div class= "user-details">
                      <%= mail_to answer.user.email %>
                    </div>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </td>
      </tr>
      <tr>
        <td class="votecell"></td>
        <td>
          <div class="comments">
            <table>
              <tbody>
                <%= render 'comments/comment', commentable: answer %>
              </tbody>
              <tfoot>
                <tr>
                  <td></td>
                  <td class="comment-form">
                    <%= render 'comments/form', commentable: answer, url_path: question_answer_comments_path(answer.question, answer) %>
                  </td>
                </tr>
              </tfoot>
            </table>
          </div>
        </td>
      </tr>
    </tbody>
  </table>
</div>

app/views/answers/_form.html.erb
<% if user_signed_in? %>
  <h2 class="space">Tu respuesta:</h2>

  <%= form_with model: answer, url: question_answers_path(question), local: true do |f| %>
    <%= render 'shared/error_messages', model: answer %>

    <div class="form-group">
      <%= f.text_area :body, rows: 5, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.submit action, class: "btn btn-primary" %>
    </div>
  <% end %>
<% end %>

app/views/comments/_comment.html.erb
<% commentable.comments.each do |comment| %>
  <tr class="comment">
      <td class="comment-actions">
      </td>
      <td class="comment-text">
        <span><%= comment.body %></span>
        –
        <a class="comment-user" href="#"></a>
        <span class="comment-date"><%= time_ago_in_words comment.created_at %></span>
      </td>
    </tr>
<% end %>

app/views/comments/_comment_questions.html.erb
<% @question.comments.each do |comment| %>
  <p>
    <hr>
    <%= comment.body %>
    <em><%= time_ago_in_words comment.created_at %></em>
  </p>
<% end %>

app/views/comments/_form.html.erb
<%# commentable = local_assigns[:commentable] %>
<% if user_signed_in? %>
  <%= form_with model: [commentable, Comment.new], url: url_path, local: true do |form| %>
    <table>
      <tbody>
        <tr>
          <td>
            <% if commentable.is_a? Question %>
              <%= form.text_area :body, class: "form-control", cols: "68", rows: "2", placeholder: "Use los comentarios para solicitar mas información o sugerir mejoras. Evite responder las preguntas en los comentarios." %>
            <% else %>
              <%= form.text_area :body, class: "form-control", cols: "68", rows: "2", placeholder: 'Use los comentarios para solicitar mas información o sugerir mejoras. Evite comentarios como "+1" o "gracias".' %>
            <% end %>
          </td>
          <td class="vt">
            <%= form.submit "Comentar", class: "btn btn-info" %>
          </td>
        </tr>
        <tr>
          <td colspan="2">
            <span class="text-counter cool">ingrese al menos 15 caracteres</span>
            <span class="form-error"></span>
          </td>
        </tr>
      </tbody>
    </table>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class='navbar-brand' href='/'>
      StackOverflow</span>
    </a>
    <form class="form-inline" action="/action_page.php">
        <input class="form-control mr-sm-2" type="text" placeholder="Search">
        <button class="btn btn-success" type="submit">Search</button>
      </form>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

    <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
      
      
      <% if user_signed_in? %>
          
          <li class="nav-item">
            <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
          <% else %>
            <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path,  class: "nav-link" %>
            </li>
            <li>
              <%= link_to "Login", new_user_session_path, class: 'nav-link'  %>
            </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OverFlowStacky</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    

  

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %> alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <%= message %>
        </div>
      <% end %>

    <%= yield %>
      </div>
  </body>
</html>

app/views/questions/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="question__header">
      <h2><%= title %></h2>
    </div>
    <div class="question__form">
      <%= form_with model: question, local: true do |f| %>
        <%= render 'shared/error_messages', model: question %>

        <div class="form-group">
          <%= f.label :title, "Titulo:" %>
          <%= f.text_field :title, class: "form-control", autofocus: true %>
        </div>

        <div class="form-group">
          <%= f.label :body, "Descripción:" %>
          <%= f.text_area :body, rows: 10, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.submit action, class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/questions/edit.html.erb
<%= render 'form', question: @question, title: "Editar Pregunta", action: "Guardar" %>

app/views/questions/index.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <% @questions.each do |question| %>
      <div class="questions" data-id="<%= question.id %>">
        <div class="questions__stats">
          <div class="questions__votes">
            <div class="questions__mini_counts">
              <span><%= question.votes.size %></span>
            </div>
            <div>Votos</div>
          </div>
          <div class="questions__answers">
            <div class="questions__mini_counts">
              <span><%= question.answers.size %></span>
            </div>
            <div>Respuestas</div>
          </div>
        </div>
        <div class="questions__summary">
          <h3>
            <%= link_to question.title, question, class: "questions__hyperlink" %>
          </h3>
          
          <div class="questions__actions">
            <%= link_to "<span class='glyphicon glyphicon-eye-open'></span> Ver"
                  .html_safe,
                  question %>
            <% if user_signed_in? && question.user == current_user %>
              <span> | </span>
              <%= link_to " <span class='glyphicon glyphicon-pencil'></span> Editar"
                    .html_safe,
                    edit_question_path(question) %>
              <span> | </span>
              <%= link_to " <span class='glyphicon glyphicon-trash'></span> Eliminar"
                    .html_safe, question,
                    method: :delete,
                    data: { confirm: "¿Estás seguro de eliminar esta pregunta?" } %>
            <% end %>
          </div>
          <div class="questions__started">
            formulada hace <%= time_ago_in_words question.created_at %>
            por <a href="#"><%= question.user.email %></a>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/new.html.erb
<%= render 'form', question: @question, title: "Publicar Pregunta", action: "Preguntar" %>

app/views/questions/show.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="question" data-id="<%= @question.id %>">
      <table>
        <tbody>
          <tr>
            <td colspan="2">
              <div class="question__header">
              <h1><%= @question.title %></h1>
            </div>
            </td>
          </tr>
          <tr>
            <td class="votecell">
              <div class="votes">
                <%= render 'votes/votes', votable: @question,
                                          create_url_path: question_votes_path(@question),
                                          destroy_url_path: question_vote_path(@question) %>
              </div>
            </td>
            <td class="question__cell">
              <div class="question__body">
                <p>
                  <%= @question.body %>
                </p>
                <table class="question__footer">
                  <tbody>
                    <tr>
                      <td class="vt">
                        <% if user_signed_in? && @question.user == current_user %>
                          <div class="question__actions">
                            <ul>
                              <li>
                                <%= link_to " <span class='glyphicon glyphicon-pencil'></span> Editar"
                                      .html_safe,
                                      edit_question_path(@question) %>
                              </li>
                              <li>
                                <%= link_to " <span class='glyphicon glyphicon-trash'></span> Eliminar"
                                      .html_safe, @question,
                                      method: :delete,
                                      data: { confirm: "¿Estás seguro de eliminar esta pregunta?" } %>
                              </li>
                            </ul>
                          </div>
                        <% end %>
                      </td>
                      <td class="user-signature">
                        <div class="user-action-time">
                          formulada hace <%= time_ago_in_words @question.created_at %>
                        </div>
                        <div class= "user-details">
                          <%= mail_to @question.user.email %>
                        </div>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </td>
          </tr>
          <tr>
            <td class="votecell"></td>
            <td>
              <div class="comments">
                <table>
                  <tbody>
                    <%= render 'comments/comment', commentable: @question %>
                  </tbody>
                  <tfoot>
                    <tr>
                      <td></td>
                      <td class="comment-form">
                        <%= render 'comments/form', commentable: @question, url_path: question_comments_path(@question) %>
                      </td>
                    </tr>
                  </tfoot>
                </table>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="answers">
      <div class="answers__header">
        <h2><%= pluralize(@question.answers.count, 'Respuesta', 'Respuestas') %>:</h2>
      </div>
      <% @answers.each do |answer| %>
        <%= render 'answers/answer', answer: answer %>
      <% end %>
      <%= render 'answers/form', question: @question, answer: @answer, action: "Publica tu respuesta" %>
    </div>
  </div>
</div>

app/views/questions/shows123.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h2>Pregunta <%= @question.id %></h2>
    <p><strong>Title: </strong><%= @question.title %></p>
    <p><strong>Body:</strong></p>
    <div><%=  @question.body %></div>
    <div>
      <% if user_signed_in? %>
        <%= link_to "Editar", edit_question_path(@question) %> |
      <% end %>
      <%= link_to "Volver", questions_path %>
    </div>

    <br>
    <h4>Votos</h4>
    <%= render 'votes/votes', votable: @question,
                              create_url_path: question_votes_path(@question),
                              destroy_url_path: question_vote_path(@question) %>

    <br>
    <h4>Comentarios:</h4>
    <%= render 'comments/comment', commentable: @question %>
    <br>
    <%= render 'comments/form', commentable: @question, url_path: question_comments_path(@question) %>

    <br>
    <h3>Respuestas:</h3><br>
    <%= render 'answers/form', question: @question, answer: @answer, action: "Responder" %>

    <% @answers.each do |answer| %>
      <%= render 'answers/answer', answer: answer %>
    <% end %>

  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-danger">
    The form contains <%= pluralize(model.errors.count, "error") %>:
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/votes/_votes.html.erb
<table>
  <tbody>
    <tr>
      <td>
        <% if votable.voted? current_user %>
          <span class='glyphicon glyphicon-triangle-top votes_on'></span>
        <% else %>
          <%= link_to create_url_path, method: :post do %>
            <span class='glyphicon glyphicon-triangle-top votes_off'></span>
          <% end %>
        <% end %>
      </td>
    </tr>
    <tr>
      <td>
        <span><%= votable.votes.count %></span>
      </td>
    </tr>
    <tr>
      <td>
        <% if votable.voted? current_user %>
          <%= link_to destroy_url_path, method: :delete do %>
            <span class='glyphicon glyphicon-triangle-bottom votes_off'></span>
          <% end %>
        <% else %>
          <span class='glyphicon glyphicon-triangle-bottom votes_off'></span>
        <% end %>
      </td>
    </tr>
  </tbody>
</table>